apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowforge-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload: prod
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: workload
            operator: Equal
            value: prod
            effect: NoSchedule
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          workload: prod
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: workload
            operator: Equal
            value: prod
            effect: NoSchedule
